repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13  # Latest release at time of writing
    hooks:
      - id: ruff-check      # Runs the linter (includes rule checks like F841, E501, etc.)
        args: [--fix]        # Auto-fix what it safely can
      - id: ruff-format     # Formats code using Ruff's Black-compatible formatter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, ., -x, ./.venv]
        pass_filenames: false

