[tool.ruff]
line-length = 100  # Still set a preferred width
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F"]  # Enable these rule sets 
                     # E = pycodestyle (style issues, like indentation, spacing, etc.)
                     # F = pyflakes (logic issues like unused variables, undefined names, etc.)
ignore = ["E501"]    # Ignore line length warnings (useful for logging or print-heavy code)
