name: Lint and Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry (if using it)
        run: |
          pip install poetry
          poetry install

      - name: Run Ruff
        run: poetry run ruff check .

      - name: Run Pytest
        run: poetry run pytest
